name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  quality:
    name: Linters, type-checks, tests
    runs-on: ubuntu-latest
    env:
      PROJECT_FILES: galactic_dynamics_bt tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Sync dependencies
        run: uv sync

      - name: flake8
        run: uv run flake8 ${PROJECT_FILES}

      - name: black (check)
        run: uv run black --check ${PROJECT_FILES}

      - name: pylint
        run: uv run pylint ${PROJECT_FILES}

      - name: pydocstyle
        run: uv run pydocstyle ${PROJECT_FILES}

      - name: mypy
        run: uv run mypy ${PROJECT_FILES}

      - name: pytest
        run: |
          mkdir -p docs/assets/generated
          uv run pytest
