name: docs

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["Release"]
    branches: [main]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build MkDocs site
    runs-on: ubuntu-latest
    # Only run if the release workflow completed successfully, or if this is a direct push without a release workflow run
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch the latest changes, including any updates from the release workflow
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Pandoc (for mkdocs-bibtex)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Sync docs deps
        run: uv sync --group docs

      - name: Generate assets
        run: |
          mkdir -p docs/assets/generated
          uv run python scripts/generate_assets.py

      - name: Build docs
        run: uv run mkdocs build --strict

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
